version: "3.9"
services:
  web:
    build: web
    restart: unless-stopped
    #tty: true
    ports:
      - 5000:5000
    environment:
      - DB_URL=postgresql://postgres:postgres@db:5432/postgres
    networks:
      - flask_network
    depends_on:
      - db
    #volumes:
    #  - on_disk:/mnt/app
  proxy:
    build: proxy
    restart: unless-stopped
    ports:
      - 80:80
    networks:
      - flask_network
  db:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - 5432:5432
    networks:
      - flask_network
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data


networks:
  flask_network:

volumes:
  postgres_data: {}
  #on_disk: