version: "3.7"
services:
  web:
    build: web
    restart: always
    ports:
      - 5000:5000
    #environment:
    #  - DEBUG=1
    networks:
      - flask_network
    depends_on:
      - db
    #volumes:
    #  - on_disk:/mnt/app
  proxy:
    build: proxy
    restart: always
    ports:
      - 80:80
    networks:
      - flask_network
  db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    networks:
      - flask_network
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=app
    volumes:
      - postgres_data:/var/lib/postgresql/data


networks:
  flask_network:

volumes:
  postgres_data:
  #on_disk: