"""empty message

Revision ID: 1d7a04f30c04
Revises: 59f5dae5c414
Create Date: 2024-05-20 20:27:00.981331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d7a04f30c04'
down_revision = '59f5dae5c414'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pixel_string2', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ran_x', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('ran_num_steps', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('ran_tan_position', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_pixel_string2_ran_num_steps'), ['ran_num_steps'], unique=False)
        batch_op.create_index(batch_op.f('ix_pixel_string2_ran_tan_position'), ['ran_tan_position'], unique=False)
        batch_op.create_index(batch_op.f('ix_pixel_string2_ran_x'), ['ran_x'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pixel_string2', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pixel_string2_ran_x'))
        batch_op.drop_index(batch_op.f('ix_pixel_string2_ran_tan_position'))
        batch_op.drop_index(batch_op.f('ix_pixel_string2_ran_num_steps'))
        batch_op.drop_column('ran_tan_position')
        batch_op.drop_column('ran_num_steps')
        batch_op.drop_column('ran_x')

    # ### end Alembic commands ###
