"""empty message

Revision ID: 1fc7c78600f7
Revises: 95b3d5e4434e
Create Date: 2024-05-16 16:06:37.198393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fc7c78600f7'
down_revision = '95b3d5e4434e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('step_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('num_steps', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('step_list', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_step_list_num_steps'), ['num_steps'], unique=False)
        batch_op.create_index(batch_op.f('ix_step_list_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_step_list_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('step_list', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_step_list_user_id'))
        batch_op.drop_index(batch_op.f('ix_step_list_timestamp'))
        batch_op.drop_index(batch_op.f('ix_step_list_num_steps'))

    op.drop_table('step_list')
    # ### end Alembic commands ###
