"""empty message

Revision ID: 241c43b083ea
Revises: 
Create Date: 2024-03-27 16:13:30.981089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '241c43b083ea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_input',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equation', sa.String(length=64), nullable=False),
    sa.Column('lower_limit', sa.String(length=16), nullable=False),
    sa.Column('upper_limit', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_input', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_input_equation'), ['equation'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_input_lower_limit'), ['lower_limit'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_input_upper_limit'), ['upper_limit'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_input', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_input_upper_limit'))
        batch_op.drop_index(batch_op.f('ix_user_input_lower_limit'))
        batch_op.drop_index(batch_op.f('ix_user_input_equation'))

    op.drop_table('user_input')
    # ### end Alembic commands ###
