"""empty message

Revision ID: 2bb94f85bc18
Revises: 1fc7c78600f7
Create Date: 2024-05-16 16:43:13.854502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bb94f85bc18'
down_revision = '1fc7c78600f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pixel_string', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pix_str', sa.String(), nullable=False))
        batch_op.drop_index('ix_pixel_string_gif_str')
        batch_op.create_index(batch_op.f('ix_pixel_string_pix_str'), ['pix_str'], unique=False)
        batch_op.drop_column('gif_str')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pixel_string', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gif_str', sa.VARCHAR(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_pixel_string_pix_str'))
        batch_op.create_index('ix_pixel_string_gif_str', ['gif_str'], unique=False)
        batch_op.drop_column('pix_str')

    # ### end Alembic commands ###
