"""users table

Revision ID: 2f732ad47d42
Revises: 241c43b083ea
Create Date: 2024-05-16 12:27:44.490845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f732ad47d42'
down_revision = '241c43b083ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('equation', sa.String(length=64), nullable=False),
    sa.Column('lower_limit', sa.String(length=16), nullable=False),
    sa.Column('upper_limit', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_equation'), ['equation'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_lower_limit'), ['lower_limit'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_session_id'), ['session_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_upper_limit'), ['upper_limit'], unique=False)

    op.create_table('user_preset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('equation', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_preset', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_preset_equation'), ['equation'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_preset_session_id'), ['session_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_preset_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('user_input', schema=None) as batch_op:
        batch_op.drop_index('ix_user_input_equation')
        batch_op.drop_index('ix_user_input_lower_limit')
        batch_op.drop_index('ix_user_input_upper_limit')

    op.drop_table('user_input')
    op.drop_table('sessions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=255), nullable=True),
    sa.Column('data', sa.BLOB(), nullable=True),
    sa.Column('expiry', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_table('user_input',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('equation', sa.VARCHAR(length=64), nullable=False),
    sa.Column('lower_limit', sa.VARCHAR(length=16), nullable=False),
    sa.Column('upper_limit', sa.VARCHAR(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_input', schema=None) as batch_op:
        batch_op.create_index('ix_user_input_upper_limit', ['upper_limit'], unique=False)
        batch_op.create_index('ix_user_input_lower_limit', ['lower_limit'], unique=False)
        batch_op.create_index('ix_user_input_equation', ['equation'], unique=False)

    with op.batch_alter_table('user_preset', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_preset_timestamp'))
        batch_op.drop_index(batch_op.f('ix_user_preset_session_id'))
        batch_op.drop_index(batch_op.f('ix_user_preset_equation'))

    op.drop_table('user_preset')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_upper_limit'))
        batch_op.drop_index(batch_op.f('ix_user_timestamp'))
        batch_op.drop_index(batch_op.f('ix_user_session_id'))
        batch_op.drop_index(batch_op.f('ix_user_lower_limit'))
        batch_op.drop_index(batch_op.f('ix_user_equation'))

    op.drop_table('user')
    # ### end Alembic commands ###
