"""empty message

Revision ID: 30b46cbbfdff
Revises: 2bb94f85bc18
Create Date: 2024-05-20 11:25:50.049682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30b46cbbfdff'
down_revision = '2bb94f85bc18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('step_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_step_list_session_id'), ['session_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('step_list', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_step_list_session_id'))
        batch_op.drop_column('session_id')

    # ### end Alembic commands ###
