"""empty message

Revision ID: 59f5dae5c414
Revises: 89b3d7375846
Create Date: 2024-05-20 16:47:07.741921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59f5dae5c414'
down_revision = '89b3d7375846'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pixel_string2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('tang_str', sa.String(), nullable=False),
    sa.Column('start_str', sa.String(), nullable=False),
    sa.Column('end_str', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pixel_string2', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pixel_string2_end_str'), ['end_str'], unique=False)
        batch_op.create_index(batch_op.f('ix_pixel_string2_session_id'), ['session_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_pixel_string2_start_str'), ['start_str'], unique=False)
        batch_op.create_index(batch_op.f('ix_pixel_string2_tang_str'), ['tang_str'], unique=False)
        batch_op.create_index(batch_op.f('ix_pixel_string2_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pixel_string2', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pixel_string2_timestamp'))
        batch_op.drop_index(batch_op.f('ix_pixel_string2_tang_str'))
        batch_op.drop_index(batch_op.f('ix_pixel_string2_start_str'))
        batch_op.drop_index(batch_op.f('ix_pixel_string2_session_id'))
        batch_op.drop_index(batch_op.f('ix_pixel_string2_end_str'))

    op.drop_table('pixel_string2')
    # ### end Alembic commands ###
