"""empty message

Revision ID: 89b3d7375846
Revises: e9a03085534e
Create Date: 2024-05-20 14:39:19.394810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89b3d7375846'
down_revision = 'e9a03085534e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mega_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('mask_start', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mega_list', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mega_list_mask_start'), ['mask_start'], unique=False)
        batch_op.create_index(batch_op.f('ix_mega_list_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_mega_list_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mega_list_x'), ['x'], unique=False)
        batch_op.create_index(batch_op.f('ix_mega_list_y'), ['y'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mega_list', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mega_list_y'))
        batch_op.drop_index(batch_op.f('ix_mega_list_x'))
        batch_op.drop_index(batch_op.f('ix_mega_list_user_id'))
        batch_op.drop_index(batch_op.f('ix_mega_list_timestamp'))
        batch_op.drop_index(batch_op.f('ix_mega_list_mask_start'))

    op.drop_table('mega_list')
    # ### end Alembic commands ###
