"""empty message

Revision ID: 95b3d5e4434e
Revises: 2f732ad47d42
Create Date: 2024-05-16 14:51:17.346103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95b3d5e4434e'
down_revision = '2f732ad47d42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pixel_string',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('gif_str', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pixel_string', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pixel_string_gif_str'), ['gif_str'], unique=False)
        batch_op.create_index(batch_op.f('ix_pixel_string_session_id'), ['session_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pixel_string', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pixel_string_session_id'))
        batch_op.drop_index(batch_op.f('ix_pixel_string_gif_str'))

    op.drop_table('pixel_string')
    # ### end Alembic commands ###
