"""empty message

Revision ID: ca0ba6fc784a
Revises: f30683d4eac2
Create Date: 2024-05-22 12:28:30.209018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca0ba6fc784a'
down_revision = 'f30683d4eac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pixel_string3', schema=None) as batch_op:
        batch_op.alter_column('ran_x',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pixel_string3', schema=None) as batch_op:
        batch_op.alter_column('ran_x',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
