"""empty message

Revision ID: e9a03085534e
Revises: 30b46cbbfdff
Create Date: 2024-05-20 11:47:47.214311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9a03085534e'
down_revision = '30b46cbbfdff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('step_list2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('num_steps', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('step_list2', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_step_list2_num_steps'), ['num_steps'], unique=False)
        batch_op.create_index(batch_op.f('ix_step_list2_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_step_list2_user_id'), ['user_id'], unique=False)

    op.drop_table('_alembic_tmp_pixel_string')
    with op.batch_alter_table('step_list', schema=None) as batch_op:
        batch_op.drop_index('ix_step_list_session_id')
        batch_op.drop_column('session_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('step_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_id', sa.INTEGER(), nullable=False))
        batch_op.create_index('ix_step_list_session_id', ['session_id'], unique=False)

    op.create_table('_alembic_tmp_pixel_string',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('session_id', sa.INTEGER(), nullable=False),
    sa.Column('gif_str', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('step_list2', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_step_list2_user_id'))
        batch_op.drop_index(batch_op.f('ix_step_list2_timestamp'))
        batch_op.drop_index(batch_op.f('ix_step_list2_num_steps'))

    op.drop_table('step_list2')
    # ### end Alembic commands ###
