"""empty message

Revision ID: f30683d4eac2
Revises: 1d7a04f30c04
Create Date: 2024-05-20 21:09:57.005814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f30683d4eac2'
down_revision = '1d7a04f30c04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pixel_string3',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('tang_str', sa.String(), nullable=False),
    sa.Column('start_str', sa.String(), nullable=False),
    sa.Column('end_str', sa.String(), nullable=False),
    sa.Column('ran_x', sa.Integer(), nullable=False),
    sa.Column('ran_num_steps', sa.Integer(), nullable=False),
    sa.Column('ran_tan_position', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pixel_string3', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pixel_string3_end_str'), ['end_str'], unique=False)
        batch_op.create_index(batch_op.f('ix_pixel_string3_ran_num_steps'), ['ran_num_steps'], unique=False)
        batch_op.create_index(batch_op.f('ix_pixel_string3_ran_tan_position'), ['ran_tan_position'], unique=False)
        batch_op.create_index(batch_op.f('ix_pixel_string3_ran_x'), ['ran_x'], unique=False)
        batch_op.create_index(batch_op.f('ix_pixel_string3_session_id'), ['session_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_pixel_string3_start_str'), ['start_str'], unique=False)
        batch_op.create_index(batch_op.f('ix_pixel_string3_tang_str'), ['tang_str'], unique=False)
        batch_op.create_index(batch_op.f('ix_pixel_string3_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('pixel_string2', schema=None) as batch_op:
        batch_op.drop_index('ix_pixel_string2_ran_num_steps')
        batch_op.drop_index('ix_pixel_string2_ran_tan_position')
        batch_op.drop_index('ix_pixel_string2_ran_x')
        batch_op.drop_column('ran_x')
        batch_op.drop_column('ran_num_steps')
        batch_op.drop_column('ran_tan_position')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pixel_string2', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ran_tan_position', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('ran_num_steps', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('ran_x', sa.INTEGER(), nullable=False))
        batch_op.create_index('ix_pixel_string2_ran_x', ['ran_x'], unique=False)
        batch_op.create_index('ix_pixel_string2_ran_tan_position', ['ran_tan_position'], unique=False)
        batch_op.create_index('ix_pixel_string2_ran_num_steps', ['ran_num_steps'], unique=False)

    with op.batch_alter_table('pixel_string3', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pixel_string3_timestamp'))
        batch_op.drop_index(batch_op.f('ix_pixel_string3_tang_str'))
        batch_op.drop_index(batch_op.f('ix_pixel_string3_start_str'))
        batch_op.drop_index(batch_op.f('ix_pixel_string3_session_id'))
        batch_op.drop_index(batch_op.f('ix_pixel_string3_ran_x'))
        batch_op.drop_index(batch_op.f('ix_pixel_string3_ran_tan_position'))
        batch_op.drop_index(batch_op.f('ix_pixel_string3_ran_num_steps'))
        batch_op.drop_index(batch_op.f('ix_pixel_string3_end_str'))

    op.drop_table('pixel_string3')
    # ### end Alembic commands ###
